#automatically downloads used PlaceholderAPI expansions which are not downloaded
automatic-expansion-downloading: true
#throw placeholderapi errors into console instead of hiding them
throw-placeholderapi-exceptions: false